### ISSUE TITLE
continuidade do projeto

### ISSUE THREAD

**Issue by erikacarvalho** [erikacarvalho/goporexemplo#4]
oi @dgv pensamos em dar continuidade ao projeto aqui no Women Who Go de Curitiba.

que acha?

**Comment by delley** [comment]
@dgv, @erikacarvalho bôra dar continuidade ao projeto?

**Comment by erikacarvalho** [comment]
@delley bora, mas como?

**Comment by marcopollivier** [comment]
Eu tava pensando esses dias nisso (em continuar o projeto já que tem exemplos faltando se comparado com o gobyexample.com) e achei hoje essa thread de vocês. Se vocês precisarem de ajuda, podem contar comigo =)

**Comment by erikacarvalho** [comment]
oi @marcopollivier , que bom saber 👊 

o @filewalkwithme tá bolando uma forma pra estruturarmos tudo pra que fique fácil de atualizar quando houver novidades no original, e depois disso vamos começar a mapear em issues o que precisa ser feito. daí a gente marca geral pra começar a distribuir \o/

**Comment by delley** [comment]
@erikacarvalho também vou adorar contribuir com o projeto!

**Comment by marcopollivier** [comment]
Maravilha, @erikacarvalho =D

**Comment by dgv** [comment]
Oi @erikacarvalho, me perdoe a demora, voltei a usar meu usuário aqui e estou retomando os projetos, você ainda teria interesse em dar continuidade ao projeto? Poderia transferi-lo para o @womenwhogocwb ?

**Comment by erikacarvalho** [comment]
@dgv mal a demora, abandonei as notificações do github por um tempo. podemos tocar sim! quando você fala em transferi-lo, seria fazermos um fork mesmo e tocar de onde parou?

**Comment by dgv** [comment]
@erikacarvalho tranquilo, não, transferi-lo mesmo para @womenwhogocwb ... vou fazer isso já... :wink:
