### ISSUE TITLE
hosting

### ISSUE THREAD

**Issue by erikacarvalho** [erikacarvalho/goporexemplo#5]
hey @dgv brigada!

como fazemos com hosting, vocês querem manter no golangbr.org ou preferem que a gente agilize isso?

**Comment by dgv** [comment]
@erikacarvalho por nada, bom, está rodando no pages e os redirectionamentos funcionando mas fica a critério de vocês manterem ou não... https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain :wink:

**Comment by erikacarvalho** [comment]
@dgv vamos manter por enquanto tudo como está, e se algo mudar nos falamos! obrigada 🤓
